// Este archivo se mantiene ejecutando scripts/refresh-training.py script

= Managing Virtual Machines with Red Hat OpenShift Virtualization (DO316)

[.big]#*Oferta relacionada*#

Este curso es parte del paquete https://www.redhat.com/es/services/training/managing-virtual-machines-red-hat-openshift-virtualization-exam[Managing Virtual Machines with Red Hat OpenShift Virtualization with exam (DO317).] El paquete está disponible con un 70 % de descuento sobre el precio de venta regional sugerido por el fabricante (MSRP) hasta el 30 de septiembre de 2025. Haz clic en "Explorar ahora" para finalizar la compra en la página del paquete y selecciona la versión autorregulada del curso más el examen para recibir la oferta. El descuento se aplicará sobre el MSRP de tu región en las ofertas aptas al finalizar la compra. No es posible combinar esta oferta con otras ofertas ni descuentos.

[.big]#*Descripción del curso*#

*Crea y gestiona máquinas virtuales en OpenShift con el operador de Red Hat OpenShift Virtualization*

En este curso, desarrollarás las habilidades fundamentales para crear y gestionar máquinas virtuales (VM) en OpenShift mediante el operador de Red Hat OpenShift Virtualization. No necesitas conocimientos previos acerca de los contenedores y Kubernetes para realizar este curso.

Con este curso, obtendrás:

* Las habilidades necesarias para crear máquinas virtuales, acceder a ellas y gestionarlas en clústeres de OpenShift
* Las habilidades necesarias para controlar el uso de la CPU, la memoria, el almacenamiento y los recursos de red de las máquinas virtuales y el acceso a todo ello mediante las mismas funciones de Kubernetes que se usarían para realizar dichas tareas en los contenedores
* Arquitecturas de muestra para gestionar la alta disponibilidad (HA) de las máquinas virtuales con las funciones y extensiones estándares de Kubernetes de OpenShift Virtualization
* Estrategias para conectar las máquinas virtuales en OpenShift a los servicios del centro de datos que estén fuera de su clúster de OpenShift, como el almacenamiento y las bases de datos
* Estrategias para migrar máquinas virtuales de hipervisores compatibles a OpenShift Virtualization mediante el uso del operador del kit de herramientas de migración para la virtualización

*Nota:* Este curso se ofrece en modalidad presencial con una duración de cuatro días, en modalidad virtual con una duración de cinco días, o como curso autorregulado. Los tiempos pueden variar conforme lo realices. Para obtener la información completa sobre el curso, el cronograma y los precios, selecciona tu ubicación y, luego, "Explorar ahora" en el menú de la derecha.

[.big]#*Resumen del contenido del curso*#

* Crear máquinas virtuales a partir de medios de instalación e imágenes de disco
* Acceder a las consolas gráficas y de texto de una máquina virtual
* Conectarse a máquinas virtuales mediante redes de Kubernetes (servicios, ingreso y rutas)
* Preparar almacenamiento en las máquinas virtuales mediante el almacenamiento de Kubernetes (PVC, PV y clases de almacenamiento)
* Iniciar, pausar y detener las máquinas virtuales
* Clonar las máquinas virtuales y generar instantáneas de ellas
* Crear y sellar imágenes de máquinas virtuales de referencia
* Conectar las máquinas virtuales con redes externas y adicionales (fuera de las redes de servicio y del pod de Kubernetes)
* Preparar los servicios del equilibrador de carga para las máquinas virtuales y, luego, usarlos para habilitar el acceso SSH a ellas
* Conectar las máquinas virtuales con el almacenamiento del host y el almacenamiento externo
* Crear máquinas virtuales a partir de tipos de instancias y plantillas de máquinas virtuales personalizadas y predefinidas
* Migrar las máquinas virtuales desde hipervisores compatibles
* Realizar backups de las máquinas virtuales y restaurarlas usando OpenShift API for Data Protection (OADP) y las herramientas de la línea de comandos

[.big]#*Público destinatario del curso*#

* Administradores de máquinas virtuales interesados en virtualizar las cargas de trabajo de los hipervisores tradicionales en OpenShift Virtualization
* Ingenieros de plataformas, administradores de nubes y de sistemas que deseen admitir cargas de trabajo virtualizadas, ya sea de forma independiente o en el mismo clúster de OpenShift en el que se encuentren las cargas de trabajo organizadas en contenedores

[.big]#*Requisitos previos para el curso*#

* https://skills.ole.redhat.com/[Debes realizar una evaluación sin costo] para determinar si esta oferta es la más conveniente en función de tus habilidades.
* Se recomienda haber realizado el curso https://www.redhat.com/es/services/training/red-hat-openshift-administration-i-operating-a-production-cluster[Red Hat OpenShift Administration I: Operating a Production Cluster (DO180)], pero no es obligatorio.
* No se requieren habilidades en Linux para gestionar los clústeres de OpenShift ni OpenShift Virtualization, pero la gestión de máquinas virtuales individuales de Linux sí las requiere, y puedes adquirirlas en los cursos siguientes:
** https://www.redhat.com/es/services/training/rh124-red-hat-system-administration-i[Red Hat System Administration I (RH124)] y https://www.redhat.com/es/services/training/rh134-red-hat-system-administration-ii[Red Hat System Administration II (RH134)] brindan los conocimientos para gestionar el sistema operativo dentro de una máquina virtual de Linux.

[.big]#*Aspectos tecnológicos que debes tener en cuenta*#

* Necesitarás acceso a ROLE para todas las entregas y el ingreso al entorno de aula remota. No existe una versión presencial y guiada por un instructor (ILT) del aula DO316.

Para más detalles, o para inscribirse:
https://www.redhat.com/es/services/training/do316-managing-virtual-machines-red-hat-openshift-virtualization
