// Este archivo se mantiene ejecutando scripts/refresh-training.py script

= Enterprise Kubernetes Storage with Red Hat OpenShift Data Foundation (DO370)

[.big]#*Descripción del curso*#

*Aprende las habilidades esenciales que se necesitan para diseñar, implementar y gestionar un clúster de Red Hat OpenShift Data Foundation y para llevar a cabo las tareas diarias de gestión del almacenamiento de Kubernetes*

Las opciones de almacenamiento tradicionales que tienen a disposición los administradores de Kubernetes son limitadas y carecen de versatilidad. Red Hat OpenShift Data Foundation ofrece beneficios concretos, incluso si tiene el respaldo del almacenamiento en la nube, como AWS EBS, o las matrices de almacenamiento de los centros de datos heredados. Muchas empresas confían en las soluciones de terceros para gestionar las backups y la recuperación ante desastres en la producción. Sin embargo, si quieren planificar su implementación de forma adecuada, necesitarán tener conocimientos sobre las API CSI y OADP para Kubernetes. En este curso, el estudiante aprenderá los pasos que debe seguir para configurar y gestionar los servicios de almacenamiento para los de los contenedores y de Kubernetes.

Después de completar el curso, tendrás acceso a los laboratorios prácticos hasta por 45 días para cualquier curso presencial que incluya un entorno virtual.

*Nota: *El curso se ofrece como clase virtual de cinco días o en la modalidad autorregulada. Los tiempos pueden variar conforme lo realices. Para conocer toda la información del curso, el cronograma y los precios, selecciona tu ubicación y, luego, el botón "Explorar ahora" en el menú de la derecha.

[.big]#*Resumen del contenido del curso*#

* Describir las características de OpenShift Data Foundation (ODF), las arquitecturas de implementación y su relación con las API de almacenamiento de Kubernetes e instalar un clúster de ODF en uno de OpenShift con el modo interno
* Seleccionar y configurar las distintas clases de almacenamiento de ODF para cumplir con los requisitos de la aplicación
* Configurar aplicaciones para usar el almacenamiento de objetos de ODF
* Configurar la supervisión, el registro y el inicio de sesión de OpenShift para usar el almacenamiento de ODF
* Realizar backups de los datos de las aplicaciones y restaurarlos con las API de CSI de Kubernetes
* Supervisar los indicadores del estado del almacenamiento de un clúster de ODF
* Identificar los elementos de Ceph Storage para Red Hat OpenShift Data Foundation y solucionar los problemas y los casos de error más comunes

[.big]#*Público al que va dirigido*#

El público al que va dirigido el curso incluye:

* Público principal: *administradores de plataforma, administradores de sistemas, administradores de nube* y otras personas que cumplan funciones de TI relacionadas con la infraestructura y sean responsables de su gestión y mantenimiento para las aplicaciones
* Público secundario: *arquitectos empresariales, ingenieros de confiabilidad del sitio, ingenieros de DevOps* y otras personas que ocupen puestos de TI relacionados con las aplicaciones y sean responsables de diseñar la infraestructura para estas

[.big]#*Capacitación recomendada*#

* https://skills.ole.redhat.com/en[Realiza una evaluación sin costo] para determinar si esta oferta es la más conveniente en función de tus habilidades.
* https://www.redhat.com/es/services/training/red-hat-certified-openshift-administrator-exam[Se recomienda haber obtenido la certificación Red Hat Certified Specialist in OpenShift Administration (EX280)] o tener conocimientos equivalentes para los puestos de trabajo de SRE o ingeniero de clústeres de Red Hat OpenShift. 
* https://www.redhat.com/es/services/training/ex200-red-hat-certified-system-administrator-rhcsa-exam[Se recomienda contar con la certificación Red Hat Certified Systems Administrator (EX200) ]o tener conocimientos equivalentes sobre la administración de los sistemas Linux para todos los puestos de trabajo.
* Si bien no es obligatorio obtener la credencial https://www.redhat.com/es/services/training/do380-red-hat-openshift-administration-iii-scaling-deployments-in-the-enterprise[Red Hat OpenShift Administration III: Scaling Deployments in the Enterprise (DO380)], los estudiantes que cuenten con ella tendrán conocimientos avanzados sobre la plataforma Red Hat OpenShift. Esto les servirá como preparación para implementar la solución Red Hat OpenShift Data Foundation (anteriormente Red Hat OpenShift Container Storage), y trabajar con ella.
* Se recomienda tener conocimientos básicos sobre Red Hat Ansible Automation Platform, aunque no es obligatorio.
* Se recomienda tener conocimientos básicos sobre las tecnologías de almacenamiento, como los tipos de disco, SAN y NAS.

[.big]#*Aspectos tecnológicos que debes tener en cuenta*#

* Necesitará acceso a ROLE para todas las entregas y el ingreso al entorno de aula remota. No existe una versión presencial y guiada por un instructor (ILT) del aula DO370.

Para más detalles, o para inscribirse:
https://www.redhat.com/es/services/training/do370-enterprise-kubernetes-storage-with-red-hat-openshift-data-foundation
